import warnings; warnings.filterwarnings('ignore')
import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('192.168.40.129', username='root', password='ncompass123', timeout=15)
def r(cmd):
    _, o, e = c.exec_command(cmd)
    out = o.read().decode('utf-8','replace').strip()
    err = e.read().decode('utf-8','replace').strip()
    if out: print(out)
    if err and 'DeprecationWarning' not in err: print('[err]', err[:300])
print('=== 本地 Docker 镜像 ===')
r('docker images --format "{{.Repository}}:{{.Tag}}\t{{.Size}}"')
print()
print('=== 运行中容器 ===')
r('docker ps --format "{{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}"')
print()
print('=== 所有容器 ===')
r('docker ps -a --format "{{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}"')
print()
print('=== nginx ===')
r('which nginx 2>/dev/null; nginx -v 2>&1 | head -1; ps aux | grep -E "nginx" | grep -v grep | head -5')
print()
print('=== Docker 镜像源配置 ===')
r('cat /etc/docker/daemon.json 2>/dev/null || echo "无配置文件"')
c.close()
print('Done')
